### ISSUE TITLE
Selection

### ISSUE THREAD

**Issue by Ahmedshubber** [efremidze/Magnetic#1]
@efremidze First of all great project. But I have one problem. How could I change it so that when one bubble is pressed I can present a new view depending on the index.

**Comment by efremidze** [comment]
yes, I'm adding that at the moment

**Comment by jackpaster** [comment]
@efremidze thank you. But how much longer do you think it might take.

**Comment by Ahmedshubber** [comment]
@efremidze I have an upwork account and there is more I want to do with this project. Would you be interested if I payed you some money to do some stuff with this project. If not thank you

**Comment by efremidze** [comment]
I already added it but I'm trying to figure out the method for delivering it. It's in the develop branch. Ill publish it in the next 24 hours.

**Comment by Ahmedshubber** [comment]
@efremidze okay but could we Skype, I have some more things I would like to do with it but you know the framework best, would you be interested in payment for adding other things to this framework

**Comment by efremidze** [comment]
I can talk tomorrow. Whats ur Skype username?

**Comment by Ahmedshubber** [comment]
@efremidze  ahmedshubber12. I think you would be very interested to see where Id like to go with this project. Out of curiosity, do you have a lot of experience with swift. Im looking for custom animations with this project. I guess we will speak tomorrow. Thanks

**Comment by efremidze** [comment]
Lets talk tomororw.

**Comment by Ahmedshubber** [comment]
@efremidze Ok thanks

**Comment by jackpaster** [comment]
Could we speak tonight at 8:00 eastern time

**Comment by efremidze** [comment]
Yes that works

**Comment by Ahmedshubber** [comment]
@efremidze by any chance are you available now to Skype

**Comment by Ahmedshubber** [comment]
@efremidze Just Skype me in the next few minutes, well talk briefly to see if your interested

**Comment by Ahmedshubber** [comment]
@efremidze we had a scheduled Skype 9 min ago. Are we still doing it

**Comment by Ahmedshubber** [comment]
@efremidze Did you take a look at the designs and description I sent you in Skype

**Comment by jackpaster** [comment]
@efremidze I thought you said you would implement the settings idea I had with this project. I checked your update, the one you posted a couple hours ago, and it looks like nothing we talked about. Could you please explain. Thanks

**Comment by efremidze** [comment]
I'm working on that seperately. It's not the main goal of this repo. I'll have more time today to finish it.

**Comment by jackpaster** [comment]
Could you please message me in Skype what the name of the repository would
be. Thanks

**Comment by jackpaster** [comment]
@efremidze hi I'm just checking in. Are you going to have it done today. You said you would be done with it three days ago. I just need to know where your at to see where I'm going to proceed with my settings. Thanks for your help and hope to hear back from you

**Comment by efremidze** [comment]
I don't have the time to implement it right now. Sorry.
