### ISSUE TITLE
Control the animation

### ISSUE THREAD

**Issue by akac** [efremidze/Magnetic#18]
What would be the best way to control the animation so the circles flying in on initialization would happen a lot faster? Ideally, I'd like them to fall in from the top or slide in from the left/right within a second.  We have about 60 circles.

**Comment by efremidze** [comment]
@IBAction func add(_ sender: UIControl?) {
        let name = UIImage.names.randomItem()
        let color = UIColor.colors.randomItem()
        let node = Node(text: name.capitalized, image: UIImage(named: name), color: color, radius: 40)
        magnetic.addChild(node)

        // apply force to node
        let force: CGFloat = 0.5
        let location = magnetic.magneticField.position
        let previous = node.position
        let x = location.x - previous.x
        let y = location.y - previous.y
        let direction = CGVector(dx: x * force, dy: y * force)
        node.physicsBody?.applyImpulse(direction)
    }
