### ISSUE TITLE
Text Position in Node

### ISSUE THREAD

**Issue by abraham28s** [efremidze/Magnetic#20]
Hi, I am kind of new at swift and I am using your Magnetic pod, however I am building and app that needs the text of the bubbles in the bottom of the bubble. Trying to do so I looked at your files but I only saw that the Y position is managed by a verticaltextalignment that can only be top, bottom, baseline and center, all of this options take the node origin as reference, I would appreciate if you could help me to set the text, in the lower position possible (higher Y position possible in the Node)
Thanks very much and sorry if my English is bad. Thank you.

**Comment by efremidze** [comment]
Try adding a newline `\n` to the text.

**Comment by abraham28s** [comment]
It didnt work. :(

**Comment by efremidze** [comment]
not even a space then a newline? `" \n\(someString)"`

**Comment by abraham28s** [comment]
I am actually using 

```
class ImageNode: Node {
        override var image: UIImage? {
            didSet {
                sprite.texture = image.map { SKTexture(image: $0) }
            }
        }
        
        override func selectedAnimation() {}
        override func deselectedAnimation() {}
    }

```
for my nodes.

I have tried even with the blankspace and the result is the same, Is there any property of the label that I can manipulate in order to achieve this? something like

`label.magicAttributeOfY = label.magicAttributeOfY + 10.0` 

I do not really know how to achieve what you said.

**Comment by efremidze** [comment]
`node.label.verticalAlignmentMode = .bottom`?
