### ISSUE TITLE
Can't set background color to UIColor.clear.

### ISSUE THREAD

**Issue by nick1ee** [efremidze/Magnetic#21]
Hi sir,

thanks for this fancy library first! But I got a problem why I tried to set the background color of magnetic to UIColor.clear, it will return me a black color. This will block the background image, could anyone advise how to address this problem?

`
    @IBOutlet weak var magneticView: MagneticView! {

        didSet {

            magnetic.magneticDelegate = self

        }

    }

    var magnetic: Magnetic {

        return magneticView.magnetic

    }

    override func viewDidLoad() {
        super.viewDidLoad()

        magnetic.allowsMultipleSelection = false

        magnetic.backgroundColor = UIColor.clear
    
    }
`

**Comment by efremidze** [comment]
Investigating

**Comment by efremidze** [comment]
You also need to set the `magneticView` background to clear.

    magneticView.backgroundColor = .clear
    magnetic.backgroundColor = .clear

<img width="411" alt="screen shot 2017-08-16 at 11 52 59 pm" src="https://user-images.githubusercontent.com/2286277/29399444-21420502-82de-11e7-98fb-2ea518c2d931.png">

**Comment by nick1ee** [comment]
Hi Lasha,

Did you tried with the 5s simulator?

I have tried your solutions, it works on my 6 plus, but I still got a black
back ground in 5s, would you please take a look?

Thank you!

2017-08-17 14:55 GMT+08:00 Lasha Efremidze <notifications@github.com>:

**Comment by efremidze** [comment]
Run on the 5s simulator
![simulator screen shot aug 17 2017 1 37 37 am](https://user-images.githubusercontent.com/2286277/29403286-bc40a438-82ec-11e7-92a8-dab447cbc267.png)

**Comment by nick1ee** [comment]
Hi Lasha,

Thanks for your test.

I have figured out a solution is to add the following code into
viewDidLoad() and all the things worked perfectly.

<magneticView.allowsTransparency = true>

Not sure why the different scenarios happened, but just share for your
information.

Thanks again!

2017-08-17 16:38 GMT+08:00 Lasha Efremidze <notifications@github.com>:
