### ISSUE TITLE
Simulator Xcode 9 - very slow

### ISSUE THREAD

**Issue by akac** [efremidze/Magnetic#22]
So I don't think this is a Magnetic issue but on Xcode 9 Sim, Magnetic is unusable. Is there a way for Simulator use to remove the animation?

**Comment by efremidze** [comment]
Any luck solving it?

**Comment by akac** [comment]
Nope. So its interesting - it works great on Xcode 9 with a 10.3 Sim, but not iOS 11 sim.

**Comment by efremidze** [comment]
it sounds like an iOS 11 simulator bug

**Comment by akac** [comment]
It may be - I did file a bug with Apple, but I still wanted you to know about it.

**Comment by alapiNode** [comment]
I am getting this error in xCode 8.3.3 when i try to run on Simulator 
Module compiled with Swift 3.0.2 cannot be imported in Swift 3.1

and same issue comes with xCode 9 again with Simulator

**Comment by efremidze** [comment]
Ill take a look.

**Comment by masuhara** [comment]
Same here. This is my environment.

・Xcode 9.0
・Swift 3.1
・ Magnetic 1.0.7

Animation is too slow, and my app was rejected for crush(but I don't know whether it causes by Magnetic.).

**Comment by piffarettig** [comment]
Same here! App is really really slow, it's a pity because the library seems great! Changed both Example project and Magnetic deployment Target to 10.3 and same errors happen. I am using Xcode 9.0

**Comment by efremidze** [comment]
Simulator?

**Comment by piffarettig** [comment]
Simulator, on device works great.

**Comment by efremidze** [comment]
Xcode 9 Simulator is buggy. Hopefully they fix sprite kit animations next release. For now please submit apple bug reports.

**Comment by piffarettig** [comment]
@efremidze Thanks!

**Comment by akac** [comment]
This is now fixed in Xcode 9.1
