### ISSUE TITLE
Nodes stuck

### ISSUE THREAD

**Issue by NPTA** [efremidze/Magnetic#23]
<img width="292" alt="screen shot 2017-09-05 at 12 31 25 am" src="https://user-images.githubusercontent.com/13376064/30038826-a3631e02-91d1-11e7-91cc-24186c954ba0.png">

When I try to repopulate the Magnetic scene I have this issue with the nodes remained on the right side of the screen. This happens on iPad Pro 12.9 inch, iOS 10.3

**Comment by efremidze** [comment]
Thanks, ill fix it asap

**Comment by NPTA** [comment]
Let me know when you finish, I want to make an update to my app but I also need iPad support :) and for this, it has to work fine on all devices.

**Comment by efremidze** [comment]
Fixed in [1.0.8](https://github.com/efremidze/Magnetic/releases/tag/1.0.8)
