### ISSUE TITLE
Using 2 spaces indentation

### ISSUE THREAD

**Issue by mlight3** [efremidze/Magnetic#25]
Hello. 

Most of swift project use 2 spaces indentation. And I think it is recommended. (just my opinion :) )
Is it okay that I convert 4 space to 2 spaces, then send PR?

If you prefer using 4 spaces, forget about this. :D

**Comment by efremidze** [comment]
I prefer 4 spaces, its the default for Xcode.

**Comment by mlight3** [comment]
@efremidze Okay! BTW I am using Xcode 8 and Xcode 9 beta and they use 2 spaces for new projects.
