### ISSUE TITLE
In Reset functionality, I want to reload the layout

### ISSUE THREAD

**Issue by AnilkumarRabhasa** [efremidze/Magnetic#30]
I want to reload layout after pressing reset option and I am getting the data from web service and I am calling that while loading the data. How to achieve this reset for reload layout?

**Comment by efremidze** [comment]
```
magnetic.children.forEach { $0.removeFromParent() }
newNodes.forEach { magnetic.addChild($0) }
```

**Comment by AnilkumarRabhasa** [comment]
Thanks so much for your valuable suggestion.
