### ISSUE TITLE
Importing Magnetic into an Obj-C project

### ISSUE THREAD

**Issue by leandrinux** [efremidze/Magnetic#34]
### New Issue Checklist

- [x] I updated Magnetic to the latest version.
- [x] I read the [Contribution Guidelines](https://github.com/efremidze/Magnetic/blob/master/.github/CONTRIBUTING.md).
- [x] I read the [documentation](https://github.com/efremidze/Magnetic).
- [x] I searched for [existing GitHub issues](https://github.com/efremidze/Magnetic/issues).

### Issue Description

I successfully imported Magnetic into an Obj-C project but later when I tried to recreate the example from the documentation I couldn't get Xcode to find the reference to the `magnetic` property of the `MagneticView` object.

This is my code:
```objc
MagneticView *magneticView = [[MagneticView alloc] initWithFrame:self.view.bounds];
self.magnetic = magneticView.magnetic; // property not found
[self.view addSubview:magneticView];
```

I wonder if someone has managed to make Magnetic work in an Obj-C project and if so, how they did it?

### Environment

- **iOS Version**: 11.1
- **Device(s)**: iPhone 6

**Comment by efremidze** [comment]
Fixed in `2.0.1`
