### ISSUE TITLE
Pod version behind on master?

### ISSUE THREAD

**Issue by JoniVR** [efremidze/Magnetic#35]
### New Issue Checklist

- [x] I updated Magnetic to the latest version.
- [x] I read the [Contribution Guidelines](https://github.com/efremidze/Magnetic/blob/master/.github/CONTRIBUTING.md).
- [x] I read the [documentation](https://github.com/efremidze/Magnetic).
- [x] I searched for [existing GitHub issues](https://github.com/efremidze/Magnetic/issues).

### Issue Description

Hi, 

Is it possible that the Pod in Cocoapods is still behind on the Github repo? 
I submitted a PR #33 some time ago to fix a warning in Xcode 9.1 and it's still showing up in my project. 
Any chance the pod still needs to be updated for that?

Thanks for your time and work.

Best regards,
Joni

**Comment by efremidze** [comment]
Fixed in `2.0.1`
