### ISSUE TITLE
While scrolling them, the bubbles are completely went out of screen

### ISSUE THREAD

**Issue by AnilkumarRabhasa** [efremidze/Magnetic#36]
Thanks for the great library. Its helped us.
But, while scrolling them horizontally, they are going out from screen and coming back, I want to control this, I just want to scroll, but, should not go out of screen. 

Where can I handle this? Can you help us?

**Comment by efremidze** [comment]
You should adjust `magnetic. physicsBody` to limit the bounds.

**Comment by AnilkumarRabhasa** [comment]
Thanks! Helped me!!

**Comment by bj97301** [comment]
@AnilkumarRabhasa would you mind sharing your solution?

**Comment by AnilkumarRabhasa** [comment]
For temporary fixes, in Node.swift files

in this method,
    open func selectedAnimation() {
        run(.scale(to: 4/3, duration: 0.2))
        if let texture = texture {
            sprite.run(.setTexture(texture))
        }
    }

I did changes in scale, so, according to your requirement you can change scale value. Hope it will helps you.
