### ISSUE TITLE
If I want to show few selected and few not selected bubbles, how to show?

### ISSUE THREAD

**Issue by AnilkumarRabhasa** [efremidze/Magnetic#37]
Thanks for great library.

But, here, I want to show while loading SKView few bubbles are already selected and few are not selected same time. 

How can I achieve this, Can you guide us.
Thanks!

**Comment by efremidze** [comment]
I'm assuming setting `isSelected` to true or false should display whether they are already selected.

**Comment by AnilkumarRabhasa** [comment]
Thanks for your quick response, but, here I am showing the layout as following code

        for data in self.dataArray {
            let color = UIColor.blue
            let node = Node(text: data, image: UIImage(named: ""), color: color, radius: 40)
            node.strokeColor = UIColor.customBGColor()
            node.label.verticalAlignmentMode = .bottom
            magnetic.addChild(node)
        }
        let indexOfA = self.dataArray.index(of: "Animation")

But, for indexOfA, I want to show this Index of item as selected, can you guide me, how can I achieve this requirement, it will more helpful to us, if you guide us. Really appreciated. Thanks!

**Comment by efremidze** [comment]
`data[indexOfA].isSelected = true`

**Comment by AnilkumarRabhasa** [comment]
I did not understand where to write this "data[indexOfA].isSelected = true", actually the above code is writing in ViewDidLoad method, by default, I am loading array of data to "        magnetic.addChild(node)".

But, same time I want to load one or few nodes are selected for particular indexes, I am able to getting which index selected, but, how can I access node here to reload and .isSelected = true, can you guide us. 

Really Appreciated. Thanks!
