### ISSUE TITLE
Image is stretched

### ISSUE THREAD

**Issue by alexandre-g** [efremidze/Magnetic#38]
### New Issue Checklist

- [x] I updated Magnetic to the latest version.
- [x] I read the [Contribution Guidelines](https://github.com/efremidze/Magnetic/blob/master/.github/CONTRIBUTING.md).
- [x] I searched for [existing GitHub issues](https://github.com/efremidze/Magnetic/issues).
- [x] I read the [documentation](https://github.com/efremidze/Magnetic).

### Issue Description

Image is shown in incorrect ratio. Probably should be aspect fill.
### Environment

- **iOS Version**: 11
- **Device(s)**: All

**Comment by efremidze** [comment]
You can add an extension to SKSpriteNode to fix the image ratio.

```
extension SKSpriteNode {
    func aspectFillToSize(fillSize: CGSize) {
        if texture != nil {
            self.size = texture!.size()
            let verticalRatio = fillSize.height / self.texture!.size().height
            let horizontalRatio = fillSize.width /  self.texture!.size().width
            let scaleRatio = horizontalRatio > verticalRatio ? horizontalRatio : verticalRatio
            self.setScale(scaleRatio)
        }
    }
}

let node = Node(text: "Italy", image: UIImage(named: "italy"), color: .red, radius: 30)
node.aspectFillToSize(view.frame.size)
magnetic.addChild(node)
```

**Comment by alexandre-g** [comment]
Hi thanks. I've found the same solution yesterday (was going to post here this morning) but do you not think this should be the default behavior? Or perhaps an option. Or if not, at the very least I think should be put into the readme?

**Comment by alexandre-g** [comment]
I've noticed that now clicking outside of the circle (and not just in the corners but to the right of some circles that have wide images as well) selects them, which conflicts if there is another circle adjacent. Any idea how to fix this?

**Comment by efremidze** [comment]
I can add an extension to the library to easily adjust the aspect ratio and ill update the readme.

Regarding the selection area, I'm not exactly sure why thats happening. Ill take a loop asap.

**Comment by efremidze** [comment]
Fixed it!

**Comment by alexandre-g** [comment]
Care to share how? :)

**Comment by efremidze** [comment]
Sorry I need to push the changes. Ill do it asap.

**Comment by efremidze** [comment]
I pushed a fix for the selection bug. [2.0.2](https://github.com/efremidze/Magnetic/releases/tag/2.0.2)

I'm still trying to find a good implementation for image aspect ratios.

**Comment by efremidze** [comment]
Fixed in [2.0.3](https://github.com/efremidze/Magnetic/releases/tag/2.0.3)

**Comment by lewis-godowski** [comment]
The image I'm setting is rather large (2000x2000), but the node is only 120x120, the image ends up at (I assume) the correct aspect ratio, but now it's at full size instead of scaled down to 120x120.

**Comment by efremidze** [comment]
Thanks, Ill take a look.

**Comment by efremidze** [comment]
Check out latest release [2.0.4](https://github.com/efremidze/Magnetic/releases/tag/2.0.4)
