### ISSUE TITLE
How to decrease the size of bubble after selected

### ISSUE THREAD

**Issue by AnilkumarRabhasa** [efremidze/Magnetic#40]
Thanks for the great library. Here, I have some issue over after selecting the bubble.

After selecting the bubble, its showing very big, I want to decrease some size, where can I change this?

Thanks!

**Comment by efremidze** [comment]
Override `func selectedAnimation()`. Please review the readme.

**Comment by AnilkumarRabhasa** [comment]
Thanks for quick response, really appreciating you.
