### ISSUE TITLE
Animation is broken when 'removeAllChildren()'

### ISSUE THREAD

**Issue by mongkonsrisin** [efremidze/Magnetic#42]
I create app that display user's profile picture in node  but I need to reload all nodes first to make sure that latest profile picture will show so I use this code to remove all nodes `magnetic.removeAllChildren()` and then display nodes. Everything works fine but animation is broken. All nodes are freeze and don't move to center screen. (Some nodes don't show too. You could compare 2 screenshots that I attached.)

If I remove `magnetic.removeAllChildren()` . Everything works fine but if user updates his photo , this page will display duplicate nodes.

What should I do. ?
Thank you.

[Screenshot when remove 'removeAllChildren()'](https://user-images.githubusercontent.com/18226423/34303727-5267f0b6-e769-11e7-83dd-c24c237b806f.png)
[Screenshot when add 'removeAllChildren()'](https://user-images.githubusercontent.com/18226423/34303728-52aa085c-e769-11e7-8b45-0529593a66a6.png)

[Code](https://pastebin.com/FfwXcn8y)

**Comment by efremidze** [comment]
Still having an issue?

**Comment by noelportugal** [comment]
I'm experiencing the same behaviour @mongkonsrisin did you found a solution?
