### ISSUE TITLE
 Value of type '[SKNode]' has no member 'compactMap'

### ISSUE THREAD

**Issue by BluePick** [efremidze/Magnetic#53]
### New Issue Checklist

- [x] I updated Magnetic to the latest version.
- [x] I read the [Contribution Guidelines](https://github.com/efremidze/Magnetic/blob/master/.github/CONTRIBUTING.md).
- [x] I read the [documentation](https://github.com/efremidze/Magnetic).
- [x] I searched for [existing GitHub issues](https://github.com/efremidze/Magnetic/issues).

### Environment

- **iOS Version**: Swift 4.0
- **XCODE**: 9.2

**File name** : Magnetic.swift

`    open var selectedChildren: [Node] { `
`        return children.compactMap { $0 as? Node }.filter { $0.isSelected }`
`   }`

**Error:**  

>  ~/Magnetic.swift:38:16: Value of type '[SKNode]' has no member 'compactMap'
> ~/Magnetic.swift:129:24: Value of type '[SKNode]' has no member 'compactMap'

**Comment by bj97301** [comment]
Can you update Xcode to 9.3?

**Comment by BluePick** [comment]
- [x] Just replace `compactMap` with  `flatMap`, all set.

**Comment by efremidze** [comment]
Thanks @BluePick
