### ISSUE TITLE
Setting an image on the node is not displaying the image.

### ISSUE THREAD

**Issue by jlubeck** [efremidze/Magnetic#56]
### New Issue Checklist

- [x] I updated Magnetic to the latest version.
- [x] I read the [Contribution Guidelines](https://github.com/efremidze/Magnetic/blob/master/.github/CONTRIBUTING.md).
- [x] I read the [documentation](https://github.com/efremidze/Magnetic).
- [x] I searched for [existing GitHub issues](https://github.com/efremidze/Magnetic/issues).

### Issue Description
Setting an image on the node is not displaying the image.

You can check the code and how the image exists prior to using it here:

![screen shot 2018-05-21 at 00 35 51](https://user-images.githubusercontent.com/3067603/40290864-14f72a8a-5c8f-11e8-80cb-93ea5030d978.png)
![screen shot 2018-05-21 at 00 35 35](https://user-images.githubusercontent.com/3067603/40290863-14a71dc4-5c8f-11e8-932b-3fa2250a2941.png)

And this is what the nodes look like:
![img_8334](https://user-images.githubusercontent.com/3067603/40290881-39776b40-5c8f-11e8-8693-e46633a5a7e3.PNG)

### Environment

- **iOS Version**: 11.3
- **Device(s)**: iPhone 7 Plus

**Comment by efremidze** [comment]
Nothing seems to be selected

**Comment by jlubeck** [comment]
Aha! I was expecting the image to appear all the time. Thanks for answering.

It appears that I can't subclass the Node class with ObjectiveC, is that correct??

**Comment by efremidze** [comment]
Is that true? It's should be subclassable.
