### ISSUE TITLE
Provide Info Window support.

### ISSUE THREAD

**Issue by himangirdhar** [efremidze/Magnetic#57]
### New Issue Checklist

- [ x] I updated Magnetic to the latest version.
- [ x] I read the [Contribution Guidelines](https://github.com/efremidze/Magnetic/blob/master/.github/CONTRIBUTING.md).
- [ x] I read the [documentation](https://github.com/efremidze/Magnetic).
- [ x] I searched for [existing GitHub issues](https://github.com/efremidze/Magnetic/issues).

### Environment

- **iOS Version**: [INSERT iOS VERSION HERE]
- **Device(s)**: [INSERT DEVICE(S) HERE]

**Comment by efremidze** [comment]
Can you please explain?

**Comment by efremidze** [comment]
This library only handles clustering. You can add an info window using a custom callout view. https://stackoverflow.com/questions/30793315/customize-mkannotation-callout-view
