### ISSUE TITLE
Wrong node's label centerY position 

### ISSUE THREAD

**Issue by ihorodnikoff** [efremidze/Magnetic#60]
### New Issue Checklist

- [x] I updated Magnetic to the latest version.
- [x] I read the [Contribution Guidelines](https://github.com/efremidze/Magnetic/blob/master/.github/CONTRIBUTING.md).
- [x] I read the [documentation](https://github.com/efremidze/Magnetic).
- [x] I searched for [existing GitHub issues](https://github.com/efremidze/Magnetic/issues).

### Issue Description
Sometimes labels Y position isn't in the center of node. This is not always observed, however, there is an assumption that specifying the width of the label affects this problem. 
<img width="545" alt="screen shot 2018-06-19 at 21 24 50" src="https://user-images.githubusercontent.com/15196687/41616695-43a4012a-7407-11e8-8064-b1a461e0bbaa.png">

### Environment

- **iOS Version**: [11.0]
- **Device(s)**: [randomly on different devices]

**Comment by efremidze** [comment]
Thanks, I'll fix asap.

**Comment by ihorodnikoff** [comment]
Thanks a lot!
I admire of your work!

**Comment by efremidze** [comment]
Fixed in [2.0.10](https://github.com/efremidze/Magnetic/releases/tag/2.0.10)
