### ISSUE TITLE
I imported magnetic pods in my project and when I'm archiving my project I got error no such module magnetic. if  I run it on simulator it works properly but when I select generic iOS device and select clean or archive I got error.

### ISSUE THREAD

**Issue by ggfggfggf** [efremidze/Magnetic#63]
### New Issue Checklist

- [ x] I updated Magnetic to the latest version.
- [x ] I read the [Contribution Guidelines](https://github.com/efremidze/Magnetic/blob/master/.github/CONTRIBUTING.md).
- [x ] I read the [documentation](https://github.com/efremidze/Magnetic).
- [ x] I searched for [existing GitHub issues](https://github.com/efremidze/Magnetic/issues).

### Environment

- **iOS Version**: [10.13.5 ]
- **Device(s)**: [INSERT DEVICE(S) HERE]

**Comment by efremidze** [comment]
This might be an issue with the Xcode beta version you're using. I'm not having any issue on the latest Xcode release.

**Comment by efremidze** [comment]
This sounds like a CocoaPods error not an error with this repo.
