### ISSUE TITLE
Expose `func node(at point: CGPoint) -> Node?` to user

### ISSUE THREAD

**Issue by puyanlin** [efremidze/Magnetic#64]
### New Issue Checklist

- [x] I updated Magnetic to the latest version.
- [x] I read the [Contribution Guidelines](https://github.com/efremidze/Magnetic/blob/master/.github/CONTRIBUTING.md).
- [x] I read the [documentation](https://github.com/efremidze/Magnetic).
- [x] I searched for [existing GitHub issues](https://github.com/efremidze/Magnetic/issues).

### Issue Description

Is there any concern about expose `func node(at point: CGPoint) -> Node?` in `Magnetic` to user?
Developers may customize their `Node` when they use this wonderful library, the customized nodes may use special `path` or in any other shapes, so can this SDK expose this func to developers?
Thank you very much.

### Environment

- **iOS Version**: [10+]
- **Device(s)**: [All iOS 10+ available devices]

**Comment by efremidze** [comment]
Exposed in 2.0.11
