### ISSUE TITLE
Spacing between bubbles

### ISSUE THREAD

**Issue by simonzwicker** [efremidze/Magnetic#65]
Hey, is it possible to add more Space between the bubbles? I checked the Code but found nothing like this

**Comment by efremidze** [comment]
You can add it by customizing the `physicsBody` of the node. I'll add options to customize it easier.

**Comment by efremidze** [comment]
I've added node spacing and custom paths to release [2.0.12](https://github.com/efremidze/Magnetic/releases/tag/2.0.12).
`let node = Node(text: name.capitalized, image: UIImage(named: name), color: color, radius: 40, path: SKShapeNode(circleOfRadius: radius).path, marginScale: 1.1)`
