### ISSUE TITLE
Expose func moveNodes(location: CGPoint, previous: CGPoint) to user

### ISSUE THREAD

**Issue by puyanlin** [efremidze/Magnetic#66]
### New Issue Checklist

- [x] I updated Magnetic to the latest version.
- [x] I read the [Contribution Guidelines](https://github.com/efremidze/Magnetic/blob/master/.github/CONTRIBUTING.md).
- [x] I read the [documentation](https://github.com/efremidze/Magnetic).
- [x] I searched for [existing GitHub issues](https://github.com/efremidze/Magnetic/issues).

### Issue Description

Is there any concern about expose `func moveNodes(location: CGPoint, previous: CGPoint)` in `Magnetic` to user?
I hope it can be exposed for developers, so we can custom drag action behavior, Thank you very much.

### Environment

- **iOS Version**: [10+]
- **Device(s)**: [All iOS 10+ available devices]

**Comment by efremidze** [comment]
Thanks, Ill expose it in the next release.

**Comment by efremidze** [comment]
Added to [2.1.2](https://github.com/efremidze/Magnetic/releases/tag/2.1.2)
