### ISSUE TITLE
Problem with name didSelected

### ISSUE THREAD

**Issue by alepiz** [efremidze/Magnetic#67]
I have a problem when I select one bubble. It doesn't recognize the name of the Node.
Please help me, thanks

LOG

didSelect -> <SKShapeNode> name:'(null)' accumulatedFrame:{{89.760002136230469, 424.89700317382812}, {147, 83}}

**Comment by efremidze** [comment]
I'll fix asap

**Comment by efremidze** [comment]
What iOS version and device?

**Comment by efremidze** [comment]
```

**Comment by alepiz** [comment]
How can I assign at each bubble a different name? For example if I select Peru it show me "name:'Peru'"
?

**Comment by alepiz** [comment]
I have iPhone X iOs version 12.0

Il giorno mar 2 ott 2018 alle ore 10:58 Lasha Efremidze <
notifications@github.com> ha scritto:

**Comment by efremidze** [comment]
Please read the documentation.

```
let node = Node(text: "Italy", image: UIImage(named: "italy"), color: .red, radius: 30)
magnetic.addChild(node)
```

**Comment by efremidze** [comment]
let node = Node(text: "Italy", image: UIImage(named: "italy"), color: .red, radius: 30)
node.name = "Italy"

**Comment by efremidze** [comment]
I'm going to close this issue since its not a bug.
