### ISSUE TITLE
Set node.strokeColor = SKColor.clear, the node is not smooth

### ISSUE THREAD

**Issue by junestchick** [efremidze/Magnetic#68]
### New Issue Checklist

- [x] I updated Magnetic to the latest version.
- [x] I read the [Contribution Guidelines](https://github.com/efremidze/Magnetic/blob/master/.github/CONTRIBUTING.md).
- [x] I read the [documentation](https://github.com/efremidze/Magnetic).
- [x] I searched for [existing GitHub issues](https://github.com/efremidze/Magnetic/issues).

### Issue Description

![image](https://user-images.githubusercontent.com/16408328/49211342-f3567e80-f3f1-11e8-8ab5-50fcbca55f9c.png)
I set others color but they are normal. Pls help. Thanks!
### Environment

- **iOS Version**: 12
- **Device(s)**: simulator

**Comment by efremidze** [comment]
SKShapeNode requires a stroke color to achieve smooth edges.
