### ISSUE TITLE
Text in label begins and ends at edge sometimes due to which some characters cuts off.

### ISSUE THREAD

**Issue by vaibhavsingla1996** [efremidze/Magnetic#76]
Text in label begins and ends at edge sometimes due to which some characters cut off.
When providing a large string for small radius, the bubble text is shifted in 2 lines or becomes edge to edge due to which first and the last character of the string is half invisible. Please add padding in bubble label.

**Comment by efremidze** [comment]
Adjust the width of the label to add padding.
`node.label.width = node.frame.width - 20`
