### ISSUE TITLE
Size to Fit Bubbles

### ISSUE THREAD

**Issue by marcelosalloum** [efremidze/Magnetic#77]
Is that possible to get the minimum magneticView size needed to fit my Nodes?

### Issue Description
Hey guys, I'd like to adjust my superview height based on the size of the MagneticView, after it's populated by the nodes. Is that a way to infer the final size of the nodes even before they've shown up?

This is how my view looks like right now:
![Simulator Screen Shot - iPhone Xs - 2019-05-26 at 18 00 33](https://user-images.githubusercontent.com/1952597/58387144-aa6a3600-7fe0-11e9-8e08-b16b9daab77c.png)

### Environment

- **iOS Version**: ios 12.2
- **Device(s)**: iPhone 8

### New Issue Checklist

- [x] I updated Magnetic to the latest version.
- [x] I read the [Contribution Guidelines](https://github.com/efremidze/Magnetic/blob/master/.github/CONTRIBUTING.md).
- [x] I read the [documentation](https://github.com/efremidze/Magnetic).
- [x] I searched for [existing GitHub issues](https://github.com/efremidze/Magnetic/issues).

**Comment by efremidze** [comment]
You can calculate the frame size using [calculateaccumulatedframe](https://developer.apple.com/documentation/spritekit/sknode/1483066-calculateaccumulatedframe).

**Comment by efremidze** [comment]
You can calculate the frame size using [calculateAccumulatedFrame()](https://developer.apple.com/documentation/spritekit/sknode/1483066-calculateaccumulatedframe).
`magneticView.calculateAccumulatedFrame()`

**Comment by marcelosalloum** [comment]
Awesome, thank you @efremidze
