### ISSUE TITLE
How can I customize it to have Image by default?

### ISSUE THREAD

**Issue by talkaboutdesign** [efremidze/Magnetic#8]
I would like to customize it so that the image is shown by default. Also the label for text is not necessary for my use. And I also need to customize what happens when you tap on it. 

Any guidance would be great.

**Comment by efremidze** [comment]
You can override the selected state function by subclassing. I'll add an example of how to achieve what you want.

**Comment by efremidze** [comment]
Subclass the Node:
```
class CustomNode: Node {
    override var image: UIImage? {
        didSet {
            guard let image = image else { return }
            sprite.texture = SKTexture(image: image)
        }
    }
    override func selectedAnimation() {}
    override func deselectedAnimation() {}
}
```
Then use the subclass:
```
let node = CustomNode(text: name.capitalized, image: UIImage(named: name), color: color, radius: 40)
magnetic.addChild(node)
```

https://github.com/efremidze/Magnetic/blob/master/Example/ViewController2.swift

**Comment by Isuru-Nanayakkara** [comment]
Hi @efremidze, the link is dead. Can you please re-add it?

**Comment by efremidze** [comment]
Look at the `ImageNode` in https://github.com/efremidze/Magnetic/blob/master/Example/ViewController.swift

**Comment by Isuru-Nanayakkara** [comment]
@efremidze Thanks!

**Comment by EdwinJr13** [comment]
It does not work anymore. How can I set the image by default in the Node? I just want nodes with images and not text.
