### ISSUE TITLE
ImageNode by default does not work anymore

### ISSUE THREAD

**Issue by EdwinJr13** [efremidze/Magnetic#82]
Hey there, 
I am struggling to set an image by default to the node. I have already used the code example but it didn't work properly. I only get a node with a color and no image.

I just want to create nodes with only images, no color, and no text.

Can someone explain me how to achieve that?

Thank you.

**Comment by VasilenkoVladislav** [comment]
@EdwinJr13, You can use fillTexture instead of texture
