### ISSUE TITLE
SPM not working due to missing `Tests` path in `MagneticTests` target

### ISSUE THREAD

**Issue by maxkupetskii** [efremidze/Magnetic#83]
After trying to add Magnetic as a dependency via SPM I got an error.

### Issue Description
File -> Swift Packages -> Add Package Dependency -> https://github.com/efremidze/Magnetic.git , 3.1.1
![Screen Shot 2019-10-24 at 10 37 33](https://user-images.githubusercontent.com/10694577/67463653-7b68f680-f64a-11e9-9699-e8ee5ec7dd71.png)

Removing 
```
        .testTarget(
            name: "MagneticTests",
            dependencies: ["Magnetic"],
            path: "Tests"
        )
```
From `Package.swift` solves the problem.

### Environment

Xcode 11.1

**Comment by efremidze** [comment]
Resolved by https://github.com/efremidze/Magnetic/releases/tag/3.1.2
