### ISSUE TITLE
Instant Crash after display magnetic view

### ISSUE THREAD

**Issue by Marcin951** [efremidze/Magnetic#84]
### New Issue Checklist

- [x] I updated Magnetic to the latest version.
- [x] I read the [Contribution Guidelines](https://github.com/efremidze/Magnetic/blob/master/.github/CONTRIBUTING.md).
- [x] I read the [documentation](https://github.com/efremidze/Magnetic).
- [x] I searched for [existing GitHub issues](https://github.com/efremidze/Magnetic/issues).

### Issue Description
randomly it crash my app, error is on the screenshot `  var magnetic: Magnetic?
    var magnetView: MagneticView!
    func loadMagnetic(){
        magnetView = MagneticView(frame: self.magneticView.bounds)
        magnetView.backgroundColor = .clear
               magnetic = magnetView.magnetic
        self.magneticView.addSubview(magnetView)
        self.magneticView.bringSubviewToFront(nextMagneticButton)
        magnetic!.backgroundColor = .clear
        
        for _ in 1...10{
            DispatchQueue.global(qos: .userInteractive).async {
                let node = Node(text: "Art", image: nil, color: UIColor.init(hexFromString: "FFFFFF", alpha: 0.15), radius: 50)
                    self.magnetic!.addChild(node)

            }
        }`
https://imgur.com/a/xEqYeBm
### Environment

- **iOS Version**: [13.3]
- **Device(s)**: [Iphone XS MAX]

**Comment by efremidze** [comment]
Is the example project crashing for you?

**Comment by Marcin951** [comment]
I noticed only when i use dispatch queue it might crash :)
