### ISSUE TITLE
SKMultilineLabelNode Support

### ISSUE THREAD

**Issue by badalpub1991** [efremidze/Magnetic#9]
How to change Lable to Multiline?

**Comment by badalpub1991** [comment]
Someone please give me the solution ? @efremidze

**Comment by efremidze** [comment]
I would fork to use a multiline label. I need to rewrite the Node using a multiline label also.

**Comment by badalpub1991** [comment]
Ok. Thanks for replay. I will wait for it. Actually multiline is required
for long names. By d way library is awsome. And very very smooth. Thanks a
lot for this.

**Comment by efremidze** [comment]
added in 1.0.5
