### ISSUE TITLE
How to move to activity when specific Node is clicked?

### ISSUE THREAD

**Issue by dvlpd** [efremidze/Magnetic#92]
- [X ] I updated Magnetic to the latest version.
- [ X] I read the [Contribution Guidelines](https://github.com/efremidze/Magnetic/blob/master/.github/CONTRIBUTING.md).
- [ X] I read the [documentation](https://github.com/efremidze/Magnetic).
- [ X] I searched for [existing GitHub issues](https://github.com/efremidze/Magnetic/issues).

Hello! I have a problem. I'm new to iOS development. 
I've seen issues 1 and 2, but didn't find any solution to my problem. 
I want to go to next specific activity after each of nodes is clicked. For instance, if you press node1 you go to Activity22, if you press node2 you go to Activity23 and so on... 
Could you please help me to solve this issue?

**Comment by jesster2k10** [comment]
You could use the `didSelectNode` delegate method and identify the node based on the text and go to the activity from that.

**Comment by dvlpd** [comment]
func magnetic(_ magnetic: Magnetic, didSelect node: Node) {
        // handle node selection

               if (node.text == "Text1") {
                performSegue(withIdentifier: "Segue1", sender: self)
            } else if (node.text == "Text2"){
                performSegue(withIdentifier: "Segue2", sender: self)
            } else {
                performSegue(withIdentifier: "Segue3", sender: self)
            }
            
        
            
        
    }

**Comment by dvlpd** [comment]
@jesster2k10 I've written today this code. However it doesn't do anything. I don't understand where the problem is... Note: "Text1, 2..." stands for text inside each Node, "Segue1, 2..." is an ID that I create and attach to each of segues created in storyboard

**Comment by dvlpd** [comment]
Any ideas? I tried every possible way to use segue programmatically but it still does not respond...
